meta_title: "2Mao - Carrefour"
meta_description: "Suas transações ainda mais seguras"
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards